name: Mosquitto broker
version: 1.0.0
bundle_id: com.eclipse-mosquitto.Mosquittobroker
app_info:
hos_version: "2024.1.0"
config_version: 1.0.0
docker_config:
    image_name: eclipse-mosquitto
    tag: 2.0.17
    container_name: Mosquittobroker
    network_mode: bridge
    icon: icon.png
    iconname: /tmp/hos/1712907560/Mosquittobroker.png
    web_ui_port: ""
    ports:
        - network_protocol: tcp
          container: "1883"
          host: "1883"
        - network_protocol: tcp
          container: "9001"
          host: "9001"
    volumes:
        - container: /mosquitto/config/mosquitto.conf
          host: /var/data/mosquitto/config/mosquitto.conf
        - container: /mosquitto/data
          host: /var/data/mosquitto/data
        - container: /mosquitto/log
          host: /var/data/mosquitto/log
    env_variables:
      - name: TZ
        value: Asia/Shanghai
    devices: []
    command: []
    privileged_mode: false
    restart_policy: "no"
    resources_limit: false
    entrypoint: /bin/sh
    maximum_cpu_usage: "0"
    memory_limit: "0"
    container_hostname: mosquitto
hdp_update_info: ""
init_script: ""
uninstall: ""
resource_files: []
author: houzzkit-team
author_introduction_url: ""
create_time: "1712907901"
update_author: ""
update_author_introduction_url: ""
hdp_create_time: ""
