name: Glances
version: 1.0.0
bundle_id: com.nicolargo.glances.Glances
app_info: app_info.md
hos_version: "2024.1.0"
config_version: 1.0.0
docker_config:
    image_name: nicolargo/glances
    tag: 3.4.0.3
    container_name: Glances
    network_mode: bridge
    icon: icon.png
    icon_name: /tmp/hos/1712909069/Glances.png
    web_ui_port: "61208"
    ports:
        - network_protocol: tcp
          container: "61208"
          host: "61208"
        - network_protocol: tcp
          container: "61209"
          host: "61209"
    volumes:
        - container: /glances/conf
          host: /var/data/glances/conf
        - container: /glances/logs
          host: /var/data//glances/logs
    env_variables:
        - name: GLANCES_OPT
          value: -w
        - name: TZ
          value: Asia/Shanghai
    devices: []
    command: []
    privileged_mode: false
    restart_policy: "no"
    resources_limit: false
    entrypoint: /bin/sh
    maximum_cpu_usage: "0"
    memory_limit: "0"
    container_hostname: Glances
hdp_update_info: ""
init_script: ""
uninstall: ""
resource_files: []
author: houzzkit-team
author_introduction_url: ""
create_time: "1712909204"
update_author: ""
update_author_introduction_url: ""
hdp_create_time: ""
