version: 1.0.0                                
step_pointer: "step1"                         
steps:        
  step1:
    step_type: run_shell_script
    parameters:
      shell_path: script.sh
      shell_info: 汉化Portainer-ce
    next_step: 'step2'
  step2:                                      
    step_type: copy_directory
    parameters:
      directory_path: '/tmp/portainer-ce-cn/*'
      write_to_path: '/var/data/portainer/public/'